name: DatabaseDeploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  pre-build-job:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'dotnet build'
      shell: pwsh
      run: |
        dotnet restore
        dotnet build --configuration Release

    - name: 'azure deploy'
      uses: azure/sql-action@v2.2
      with:
        connection-string: ${{ secrets.CONNECTION_STRING }}
        path: 'sqldb-deploy-using-fed/SqldbDeployUsingEntraFed/obj/Release/netstandard2.0/SqldbDeployUsingEntraFed.dacpac'
        action: 'Publish'

    - name: Logout
      run: az logout