trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  project: '**/WpfAppDeployUsingAzureDevOps/**/*.csproj'

steps:
## NuGet Restore
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '$(project)'

## Test
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(project)'

## Build
- task: DotNetCoreCLI@2
  inputs:
    command: build
    arguments: -c Release
    projects: '$(project)'

## Publish
- task: MSBuild@1
  inputs:
    solution: '**/WpfAppDeployUsingAzureDevOps/**/*.csproj'
    configuration: Release
    msbuildArguments: /t:Publish /p:Day=127 /p:BuildNumber=12

## CopyFile
- task: CopyFiles@2
  inputs:
    contents: '**\bin\Release\**\publish\*.exe'
    targetFolder: '$(build.artifactstagingdirectory)'

## Publish To Drop
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactstagingdirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
