trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  project: '**/WpfAppDeployUsingAzureDevOps/**/*.csproj'
  days: 0

steps:
# Calc Build Settings
- task: PowerShell@2
  inputs:
      targetType: inline
      script: |
        $baseDate = [datetime]"02/06/2020"
        $currentDate = $(Get-Date)
        $interval = NEW-TIMESPAN -Start $baseDate -End $currentDate
        $days = $interval.Days
        Write-Host "##vso[task.setvariable variable=days]$days"
        echo $days

## NuGet Restore
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '$(project)'

## Test
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(project)'

## Build
- task: DotNetCoreCLI@2
  inputs:
    command: build
    arguments: -c Release
    projects: '$(project)'

## Publish
- task: MSBuild@1
  inputs:
    solution: '**/WpfAppDeployUsingAzureDevOps/**/*.csproj'
    configuration: Release
    msbuildArguments: /t:Publish /p:Day=$(days) /p:BuildNumber=12

## CopyFile
- task: CopyFiles@2
  inputs:
    contents: '**\bin\Release\**\publish\*.exe'
    flattenFolders: true
    targetFolder: '$(build.artifactstagingdirectory)'

## Publish To Drop
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactstagingdirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
