trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  project: '**/WpfAppDeployUsingAzureDevOps/**/*.csproj'
  days: 0
  dayinterval: 0
  subscrption: 従量課金(ad7805a2-0c71-4457-93b0-985d031ab10b)

steps:
# Calc Build Settings
- task: PowerShell@2
  displayName: 'Calc Build Version'
  inputs:
      targetType: inline
      script: |
        $baseDate = [datetime]"06/02/2020"
        $currentDate = $(Get-Date)
        $interval = NEW-TIMESPAN -Start $baseDate -End $currentDate
        $days = $interval.Days
        Write-Host "##vso[task.setvariable variable=days]$days"
        echo $days
        $today = Get-Date -f d
        $startdate = Get-Date $today
        $todayinterval = NEW-TIMESPAN -Start $startdate -End $currentDate
        $dayinterval = [Math]::Truncate($todayinterval.TotalMinutes)
        Write-Host "##vso[task.setvariable variable=dayinterval]$dayinterval"
        echo $dayinterval

## NuGet Restore
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '$(project)'

## Test
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(project)'

## Build
- task: DotNetCoreCLI@2
  inputs:
    command: build
    arguments: -c Release
    projects: '$(project)'

## Publish
- task: MSBuild@1
  inputs:
    solution: '**/WpfAppDeployUsingAzureDevOps/**/*.csproj'
    configuration: Release
    msbuildArguments: /t:Publish /p:Day=$(days) /p:BuildNumber=$(dayinterval)

## CopyFile
- task: CopyFiles@2
  inputs:
    contents: '**\bin\Release\**\publish\*.exe'
    flattenFolders: true
    targetFolder: '$(build.artifactstagingdirectory)'

## Publish To Drop
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactstagingdirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'

# Upload
- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(build.artifactstagingdirectory)\drop'
    azureSubscription: '従量課金(ad7805a2-0c71-4457-93b0-985d031ab10b)'
    Destination: 'AzureBlob'
    storage: 'appcontainer'
    ContainerName: 'application'